name: Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  SITE_URL: http://[::]:3000
  CYPRESS_BASE_URL: http://[::]:3000

jobs:
  code-quality-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: npx ci

      - name: Prettier
        run: npm run format

      - name: ESLint
        run: npm run lint

      - name: TypeCheck
        run: npm run typecheck
